sudo: required

services:
  - docker

language: java
dist: bionic

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_IMAGE=uroshekic/rso-media:1.0-SNAPSHOT-$TRAVIS_JOB_NUMBER

script:
  - mvn clean package -U
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker build -t "$DOCKER_IMAGE" .; fi

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
